# Generated by Django 3.1.3 on 2021-03-19 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupes',
            fields=[
                ('IdGroupe', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Groupe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('Tag', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SousGroupes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SousGroupe', models.CharField(max_length=50)),
                ('IdGroupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.groupes')),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('Devui', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('IdLora', models.CharField(max_length=50)),
                ('IdGroupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.groupes')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.tags')),
            ],
        ),
    ]
