# Generated by Django 3.1.3 on 2021-03-19 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20210319_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('Devui', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('IdLora', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('IdGroupe', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Groupe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SousGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SousGroupe', models.CharField(max_length=50)),
                ('IdGroupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('Tag', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='sousgroupes',
            name='IdGroupe',
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
        migrations.DeleteModel(
            name='Groupes',
        ),
        migrations.DeleteModel(
            name='SousGroupes',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='device',
            name='IdGroupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.groupe'),
        ),
        migrations.AddField(
            model_name='device',
            name='Tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.tag'),
        ),
    ]
