# Generated by Django 3.1.3 on 2021-03-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20210319_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Tag',
        ),
        migrations.AddField(
            model_name='device',
            name='Tag',
            field=models.ManyToManyField(to='interface.Tag'),
        ),
        migrations.DeleteModel(
            name='SousGroupe',
        ),
    ]
